# Site settings
title: "Resume"
description: "A resume template for GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "VAMSI KALYAN JUPUDI"
resume_title:                   "Trojan | Ex-IBMer | Programmer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kalyan.jupudi@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 3344346318"
resume_contact_address:         "201 University Ave,Unit 600, Troy, AL, USA 36081"

resume_header_contact_info:     "Troy, AL, USA • 3344346318 • kalyan.jupudi@outlook.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a skilled software developer with experience at IBM, I am passionate about using technology to solve complex problems and drive innovation. My expertise spans a broad range of technologies, including IBM cloud, Python, C, JavaScript, Node.js, Angular, Cypress, recommendation system, machine learning, system design, object-oriented programming, Java, Express, Fastapi, devsecops, Elastic Search, Solr, and Cron jobs.

I hold several certifications, including IBM Cloud Advocate, IBM Cloud Technical Advocate, IBM DevSecOps, and SAP on IBM Cloud Specialty, which demonstrate my commitment to staying on the cutting edge of industry developments. I take pride in my ability to automate tasks that consume significant amounts of time, and I have consistently earned the highest performance ratings and recognition for my productivity and creativity.

Throughout my career, I have worked on diverse projects and collaborated with cross-functional teams to implement innovative solutions that meet and exceed customer needs. As a driven and ambitious professional, I am excited to leverage my skills and experience to take on new challenges and make meaningful contributions to the technology industry.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/JUPUDI-VAMSI-KALYAN"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/vamsikalyan9090/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://jupudi-vamsi-kalyan.github.io/Resume/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
